kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-configmap
  namespace: default
  labels:
    spring.cloud.kubernetes.config.informer.enabled: 'true'
    spring.cloud.kubernetes.config: 'true'
  annotations:
    spring.cloud.kubernetes.configmap.apps: 'sample-in-a, sample-in-default'
data:
  my.property: "changed"
