---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-in-a
  namespace: a
  labels:
    app: sample-in-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-in-a
  template:
    metadata:
      labels:
        app: sample-in-a
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: sample-in-a
          image: "sample:latest"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP

        # only needed if you want bootstrap enabled
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "TRUE"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-in-default
  labels:
    app: sample-in-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-in-default
  template:
    metadata:
      labels:
        app: sample-in-default
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: sample-in-default
          image: "sample:latest"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP

          # only needed if you want bootstrap enabled
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "TRUE"
