---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: sample
          image: "sample:latest"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP

          env:
            - name: SPRING_CONFIG_IMPORT
              value: "kubernetes:"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
