---

apiVersion: v1
kind: Service
metadata:
  name: sample-in-a
  namespace: a
  labels:
    app: sample-in-a
spec:
  selector:
    app: sample-in-a
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: sample-in-default
  labels:
    app: sample-in-default
spec:
  selector:
    app: sample-in-default
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
