apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-kubernetes-configuration-watcher
  labels:
    app: spring-cloud-kubernetes-configuration-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-configuration-watcher
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: spring-cloud-kubernetes-configuration-watcher
          # change this to 3.1.4, as I am using a custom locally build image
          image: docker.io/springcloud/spring-cloud-kubernetes-configuration-watcher:3.1.5-SNAPSHOT
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/liveness
          ports:
            - containerPort: 8888
          env:
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES
              value: DEBUG
            # what namespace is config watcher supposed to track for config maps
            - name: SPRING_CLOUD_KUBERNETES_RELOAD_NAMESPACES_0
              value: "default"

            # disable reload of config watcher itself
            - name: SPRING_CLOUD_KUBERNETES_RELOAD_ENABLED
              value: "FALSE"

              # we do not need to monitor secrets, so ignore them completely
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLED
              value: "FALSE"

            # only config maps that have the label
            # "spring.cloud.kubernetes.config.informer.enabled: 'true'" will be tracked
            - name: SPRING_CLOUD_KUBERNETES_RELOAD_ENABLERELOADFILTERING

            # after a change is observed, how much time to delay sending refresh
              value: "TRUE"
            - name: SPRING_CLOUD_KUBERNETES_CONFIGURATION_WATCHER_REFRESHDELAY
              value: "5000"

              # by default, both reactive and blocking discovery implementations
              # are enabled, we only need reactive, so disable blocking
            - name: SPRING_CLOUD_DISCOVERY_BLOCKING_ENABLED
              value: "FALSE"

            # what namespaces is discovery client (that config watcher uses)
            # supposed to look for services
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_NAMESPACES_0
              value: "a"
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_NAMESPACES_1
              value: "default"




